# Generated by Django 4.0.6 on 2022-08-03 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('books', '0002_book_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
