# Generated by Django 4.0.6 on 2022-08-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
